=== lavenderca/scipion-docker/scipion/software/em/xmipp/applications/test_programs/test.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/test.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE XMIPP_TESTS SYSTEM "test.dtd">

    <XMIPP_TESTS>
    ...
    </XMIPP_TESTS>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT XMIPP_TESTS (PROGRAM)*>

<!--- Put your DTDDoc comment here. -->
<!--random true if output of two execution may be different-->
<!ELEMENT PROGRAM (CASE)*>
<!ATTLIST PROGRAM
    random CDATA #IMPLIED
    mpi CDATA #IMPLIED
    name CDATA #IMPLIED
    owner CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CASE (PRERUN|POSTRUN|FILE)*>
<!ATTLIST CASE
    arguments CDATA #IMPLIED
    changeDir CDATA #IMPLIED
    random    CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PRERUN EMPTY>
<!ATTLIST PRERUN
    command CDATA #IMPLIED
  >
  
<!ELEMENT POSTRUN EMPTY>
<!ATTLIST POSTRUN
    command CDATA #IMPLIED
  >
  
<!ELEMENT FILE EMPTY>
<!ATTLIST FILE
    filename CDATA #IMPLIED
  >

=== lavenderca/scipion-docker/scipion/software/em/xmipp/applications/test_programs/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE XMIPP_TESTS SYSTEM "test.dtd">
<XMIPP_TESTS>
	<PROGRAM name="xmipp_angular_break_symmetry" mpi="FALSE"
		owner="rmarabini">
		<CASE
			arguments="-i input/i3.xmd -o %o/i3_v2.xmd --sym i3"
			changeDir="FALSE">
               <POSTRUN
                command='xmipp_angular_distance --ang1 input/i3.xmd --ang2 %o/i3_v2.xmd --sym i3  --oroot %o/OUT'/>
                        <FILE filename="OUT_vec_diff_hist.txt"/>
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_angular_discrete_assign" mpi="FALSE"
		owner="rmarabini">
		<CASE
			arguments="-i input/aFewProjections.sel -o %o/assigned_angles.txt --ref %o/reference.doc"
			changeDir="FALSE">
			<PRERUN
				command="xmipp_angular_project_library -i input/phantomBacteriorhodopsin.vol -o %o/reference.stk --sampling_rate 10" />
                        <FILE filename="assigned_angles.txt"/>
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_angular_distance" mpi="FALSE" owner="coss">
		<CASE
			arguments="--ang1 input/discreteAssignment.xmd --ang2 input/aFewProjections.sel --oroot %o/angleComparison --sym c3 -v 2"
			changeDir="FALSE">
			<FILE filename="angleComparison.xmd" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_angular_distribution_show" mpi="FALSE"
		owner="rmarabini">
		<CASE
			arguments="-i input/randomAngularDistribution.sel -o %o/distribution.xmd histogram"
			changeDir="FALSE">
			<FILE filename="distribution.xmd" />
		</CASE>
		<CASE
			arguments="-i input/randomAngularDistribution.sel -o %o/distribution.bild chimera"
			changeDir="FALSE">
			<FILE filename="distribution.bild" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_angular_neighbourhood" mpi="FALSE" owner="rmarabini">
		<CASE
			arguments="-i1 input/randomAngularDistribution.sel -i2 input/aFewProjections.sel -o %o/neighborhood.sel"
			changeDir="FALSE">
			<FILE filename="neighborhood.sel" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_angular_project_library" mpi="FALSE"
		owner="rmarabini">
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
		</CASE>
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5 --compute_neighbors --experimental_images input/aFewProjections.sel  --angular_distance -1"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
			<FILE filename="output_projections_sampling.xmd" />
		</CASE>
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5 --compute_neighbors --experimental_images input/aFewProjections.sel  --angular_distance 10"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
			<FILE filename="output_projections_sampling.xmd" />
		</CASE>
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5 --compute_neighbors --experimental_images input/aFewProjections.sel  --angular_distance 10 --near_exp_data"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
			<FILE filename="output_projections_sampling.xmd" />
		</CASE>
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5 --method real_space"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
		</CASE>

	</PROGRAM>
	<PROGRAM name="xmipp_mpi_angular_project_library" mpi="TRUE"
		owner="rmarabini">
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
		</CASE>
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5 --compute_neighbors --experimental_images input/aFewProjections.sel  --angular_distance -1"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
			<FILE filename="output_projections_sampling.xmd" />
		</CASE>
		<CASE
			arguments="-i input/phantomBacteriorhodopsin.vol -o %o/output_projections.stk --sym c6 --sampling_rate 5 --compute_neighbors --experimental_images input/aFewProjections.sel  --angular_distance 10"
			changeDir="FALSE">
			<FILE filename="output_projections.doc" />
			<FILE filename="output_projections.stk" />
			<FILE filename="output_projections_sampling.xmd" />
		</CASE>

	</PROGRAM>
	<PROGRAM name="xmipp_mpi_angular_projection_matching" mpi="TRUE"
		owner="rmarabini">
		<CASE
			arguments="-i input/aFewProjections.sel -o %o/assigned_angles.xmd --ref %o/reference.stk"
			changeDir="FALSE">
			<PRERUN
				command="xmipp_angular_project_library -i input/phantomBacteriorhodopsin.vol --experimental_images input/aFewProjections.sel -o %o/reference.stk --sampling_rate 10 --compute_neighbors --angular_distance -1" />
			<FILE filename="reference.doc" />
			<FILE filename="reference_sampling.xmd" />
			<FILE filename="reference.stk" />
			<FILE filename="assigned_angles.xmd" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_angular_projection_matching" owner="rmarabini">
		<CASE
			arguments="-i input/aFewProjections.sel -o %o/assigned_angles.xmd --ref %o/reference.stk --thr 3"
			changeDir="FALSE">
			<PRERUN
				command="xmipp_angular_project_library -i input/phantomBacteriorhodopsin.vol --experimental_images input/aFewProjections.sel -o %o/reference.stk --sampling_rate 10 --compute_neighbors --angular_distance -1" />
			<FILE filename="reference.doc" />
			<FILE filename="reference_sampling.xmd" />
			<FILE filename="reference.stk" />
			<FILE filename="assigned_angles.xmd" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_angular_rotate" mpi="FALSE" owner="coss">
		<CASE
			arguments="-i input/aFewProjections.sel --axis 10 1 2 3 -o %o/newAnglesFewProjections.sel"
			changeDir="FALSE">
			<FILE filename="newAnglesFewProjections.sel" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_classify_analyze_cluster" mpi="FALSE"
		owner="coss">
		<CASE
			arguments="-i input/smallStack.stk --ref 1@input/smallStack.stk -o %o/pca.xmd"
			changeDir="FALSE">
			<FILE filename="pca.xmd" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_classify_compare_classes" mpi="FALSE"
		owner="coss">
		<CASE
			arguments="--i1 input/CL2DBacteriorhodopsin/level_00/class_classes.xmd --i2 input/CL2DBacteriorhodopsin/level_01/class_classes.xmd -o %o/classes_hierarchy.txt"
			changeDir="FALSE">
			<FILE filename="classes_hierarchy.txt" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_classify_evaluate_classes" mpi="FALSE"
		owner="coss">
		<CASE
			arguments="-i input/CL2DBacteriorhodopsin/level_00/class_classes.xmd -o %o/evaluated_classes.xmd"
			changeDir="FALSE">
			<FILE filename="evaluated_classes.xmd" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_classify_kerdensom" mpi="FALSE" owner="coss">
		<CASE
			arguments="-i input/clusterVectors.xmd --oroot %o/kerdensom --deterministic_annealing 1"
			changeDir="FALSE" random="TRUE">
			<!-- random check skip files -->
			<FILE filename="kerdensom_vectors.vec" />
			<FILE filename="kerdensom_vectors.xmd" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_ctf_correct_wiener3d" mpi="FALSE" owner="rmarabini">
		<CASE arguments="-i input/ctf_correct3d.xmd --oroot %o/wiener"
			changeDir="FALSE">
			<FILE filename="wiener_deconvolved.vol" />
			<FILE filename="wiener_ctffiltered_group000001.vol" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_ctf_correct_idr" mpi="FALSE" owner="coss">
		<CASE
			arguments="-i input/projectionsBacteriorhodopsinWithCTF.sel --vol input/phantomBacteriorhodopsin.vol -o %o/idr.stk"
			changeDir="FALSE">
			<FILE filename="idr.stk" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_ctf_create_ctfdat" mpi="FALSE" owner="coss">
		<CASE
			arguments="-i input/micrographs.xmd --ctfs input/ctfs.xmd --oroot %o/output"
			changeDir="FALSE">
			<FILE filename="output.ctfdat" />
		</CASE>
		<CASE
			arguments="-i input/micrographs.xmd --defocus input/defocus.xmd input/input.ctfparam --oroot %o/output"
			changeDir="FALSE">
			<FILE filename="output.ctfdat" />
			<FILE filename="output000001.ctfparam" />
			<FILE filename="output000002.ctfparam" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_ctf_enhance_psd" mpi="FALSE" owner="coss">
		<CASE
			arguments="-i input/down1_01nov26b.001.001.001.002_Periodogramavg.psd -o %o/enhanced_psd.xmp"
			changeDir="FALSE">
			<FILE filename="enhanced_psd.xmp" />
		</CASE>
	</PROGRAM>
	<PROGRAM name="xmipp_ctf_estimate_from_micrograph" mpi="FALSE"
		owner="jvargas">
		<CASE
			arguments="--micrograph input/Protocol_Preprocess_Micrographs/Micrographs/01nov26b.001.001.001.002.mrc --oroot %o/micrograph --dont_estimate_ctf"
			changeDir="FALSE">
			<FILE filename="micrograph.psd" />
		</CASE>
		<CASE
			arguments="--micrograph input/Protocol_Preprocess_Micrographs/Micrographs/01nov26b.001.001.001.002.mrc --oroot %o/micrograph --sampling_rate 1.4 --voltage 200 --spherical_aberration 2.5 --pieceDim 256 --downSamplingPerformed 2.5 --ctfmodelSize 256  --defocusU 14900 --defocusV 14900 --min_freq 0.01 --max_freq 0.4"
			changeDir="FALSE">
            <POSTRUN
                command="xmipp_metadata_utilities -i %o/micrograph.ctfparam --operate keep_column 'ctfDefocusU ctfDefocusV' -o %o/Defocus.xmd" />
            <POSTRUN
                command='xmipp_metadata_utilities -i %o/Defocus.xmd --operate  modify_values "ctfDefocusU = round(ctfDefocusU/100.0)" '/>
            <POSTRUN
                command='xmipp_metadata_utilities -i %o/Defocus.xmd --operate  modify_values "ctfDefocusV = round(ctfDefocusV/100.0)" '/>
			<FILE filename="micrograph.psd" />
